# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [4]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
array1 = np.array([1,2,3,4,5])


# Create a 2-dimensional NumPy array using np.array()
# array2 = np.array([1,2,3],[4,5,6])
array2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
array3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
array1.shape, array1.ndim, array1.dtype, array1.size, type(array1)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [7]:
# Attributes of 2-dimensional array
array2.shape, array2.ndim, array2.dtype, array2.size, type(array2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [8]:
# Attributes of 3-dimensional array
array3.shape, array3.ndim, array3.dtype, array3.size, type(array3)

((1, 3, 3), 3, dtype('int64'), 9, numpy.ndarray)

In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
pd.DataFrame(array1)
pd.DataFrame(array2)

0  1  2
0  1  2  3
1  4  5  6

In [10]:
# Create an array of shape (10, 2) with only ones
array_ones = np.ones((10,2))
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
# Create an array of shape (7, 2, 3) of only zeros
array_zeros = np.zeros(shape=(7,2,3))
array_zeros


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
# Create an array within a range of 0 and 100 with step 3 arr = np.array(0,100,step=3)
arr = np.arange(0,100,step=3)
arr


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [13]:
# Create a random array with numbers between 0 and 10 of size (7, 2) arr2 = np.array(0,10,shape=(7,2))
arr2 = np.random.randint(0,10,size=(7,2))
arr2

array([[1, 2],
       [1, 0],
       [7, 8],
       [4, 9],
       [0, 8],
       [0, 6],
       [6, 9]])

In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5) arr3 = np.random.random(0,1,shape=(3,5))
arr3 = np.random.random(size=(3,5))
arr3


array([[0.5093247 , 0.46380589, 0.83520371, 0.5020146 , 0.91840806],
       [0.5267098 , 0.50179609, 0.76401865, 0.36954376, 0.40255984],
       [0.37789635, 0.19959042, 0.48114475, 0.21599808, 0.12251549]])

In [15]:
# Set the random seed to 42 np.random(seed=42)
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr4 = np.random.randint(0,10,size=(4,6))
arr4


# Create a random array of numbers between 0 & 10 of size (4, 6)


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [16]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable arr5 =np.random.randint(1,10,shape=(3,7))
arr5 = np.random.randint(1,10,size=(3,7))
arr5
np.unique(arr5)


# Find the unique numbers in the array you just created


array([1, 2, 3, 4, 5, 7, 9])

In [17]:
# Find the 0'th index of the latest array you created arr5[0]
arr5[0]


array([9, 1, 3, 7, 4, 9, 3])

In [18]:
# Get the first 2 rows of latest array you created arr5[:2]
arr5[:2]


array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [19]:
# Get the first 2 values of the first 2 rows of the latest array [arr5[:2,:2]]
arr5[:2,:2]

array([[9, 1],
       [5, 3]])

In [20]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables arr = np.array(0,10,size=(3,5)) arr_1 = np.ones(3,5)
arr = np.random.randint(0,10,size=(3,5))
arr_1 = np.ones(shape=(3,5))
arr

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [21]:
# Add the two arrays together
arr+arr_1

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [22]:
# Create another array of ones of shape (5, 3)
arr_1_2 = np.ones(shape=(5,3))
arr_1_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# Try add the array of ones and the other most recent array together
arr_1+arr_1_2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [25]:
# Create another array of ones of shape (3, 5)
arr_1_3 = np.ones(shape=(3,5))
arr_1_3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
# Subtract the new array of ones from the other most recent array
arr-arr_1_3

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [27]:
# Multiply the ones array with the latest array
arr_1*arr

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [28]:
# Take the latest array to the power of 2 using '**'
arr**2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [29]:
# Do the same thing with np.square()
np.square(arr)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [30]:
# Find the mean of the latest array using np.mean()
np.mean(arr)

3.8666666666666667

In [31]:
# Find the maximum of the latest array using np.max()
np.max(arr)

9

In [32]:
# Find the minimum of the latest array using np.min()
np.min(arr)

0

In [33]:
# Find the standard deviation of the latest array
np.std(arr)

2.578543947441829

In [34]:
# Find the variance of the latest array
arr.var()

6.648888888888889

In [35]:
# Reshape the latest array to (3, 5, 1)
arr.reshape(3,5,1)

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [36]:
# Transpose the latest array
arr.transpose()

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

In [37]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 =np.random.randint(0,10,size=(3,3))
arr2 =np.random.randint(0,10,size=(3,2))
arr1,arr2

(array([[9, 1, 9],
        [3, 7, 6],
        [8, 7, 4]]),
 array([[1, 4],
        [7, 9],
        [8, 8]]))

In [38]:
# Perform a dot product on the two newest arrays you created
arr1.dot(arr2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [39]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr3 =np.random.randint(0,10,size=(4,3))
arr4 =np.random.randint(0,10,size=(4,3))
arr3,arr4


(array([[0, 8, 6],
        [8, 7, 0],
        [7, 7, 2],
        [0, 7, 2]]),
 array([[2, 0, 4],
        [9, 6, 9],
        [8, 6, 8],
        [7, 1, 0]]))

In [40]:
# Perform a dot product on the two newest arrays you created
arr3.dot(arr4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [41]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
arr3.dot(arr4.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [42]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables a1 = np.random.randint(0,10,size=(3,2)) a2=np.random.randint(0,10,size=(3,2))
np.random.seed(0)
a1 = np.random.randint(0,10,size=(3,2))
a2 = np.random.randint(0,10,size=(3,2))
a1,a2

(array([[5, 0],
        [3, 3],
        [7, 9]]),
 array([[3, 5],
        [2, 4],
        [7, 6]]))

In [43]:
# Compare the two arrays with '>'
a1>a2

array([[ True, False],
       [ True, False],
       [False,  True]])

What happens when you compare the arrays with `>`?

In [44]:
# Compare the two arrays with '>='
a1>=a2

array([[ True, False],
       [ True, False],
       [ True,  True]])

In [45]:
# Find which elements of the first array are greater than 7
a1>7

array([[False, False],
       [False, False],
       [False,  True]])

In [46]:
# Which parts of each array are equal? (try using '==')
a1==a2

array([[False, False],
       [False, False],
       [ True, False]])

In [47]:
# Sort one of the arrays you just created in ascending order
np.sort(a1)

array([[0, 5],
       [3, 3],
       [7, 9]])

In [48]:
# Sort the indexes of one of the arrays you just created
np.argsort(a1)

array([[1, 0],
       [0, 1],
       [0, 1]])

In [49]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a1)

5

In [50]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a1)

1

In [51]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a1,axis=1)

array([0, 0, 1])

In [52]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a1,axis=0)

array([1, 0])

In [53]:
# Create an array of normally distributed random numbers
arr = np.random.randn(3,5)
arr

array([[-0.05503512, -0.10731045,  1.36546718, -0.09769572, -2.42595457],
       [-0.4530558 , -0.470771  ,  0.973016  , -1.27814912,  1.43737068],
       [-0.07770457,  1.08963016,  0.09654267,  1.41866711,  1.16827314]])

In [57]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr = np.linspace(1,100,10)
arr

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.